### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by IT21051470** [Pixens/Discord-Token-Mail-Verifier#5]
[-] Failed to verify mail | MTEzODM0NzQ5Nzc0ODcwOTM3Ng.GX_BKI.89dtpaMrcTyvO5Tb00pFdPf5RwuYTCWxbDZbCg
[-] Failed to verify mail | MTEzODM0NzUyNzg0NzAzODk5Nw.Gl9ib4.RxDIyp7D8sLg_gL4v2zbwl8zFL0LR2BajpGT98
[-] Failed to verify mail | MTEzODM0NzQxNDAyMjAwMDc4MQ.G2O0je.JbKMFpdSkkZyIWNCaorH4__FcKul29_0btJbkk
[-] Failed to verify mail | MTEzODM0NzQxNTczNzQ2Njk4MQ.GudCH_.VEev5jEI0rbDHRlKK7tx5iy8Pwv1PbsSoPamZQ
Invalid URL 'ACTIVATION_CANCELED': No scheme supplied. Perhaps you meant https://ACTIVATION_CANCELED?
Invalid URL 'ACTIVATION_CANCELED': No scheme supplied. Perhaps you meant https://ACTIVATION_CANCELED?
Invalid URL 'ACTIVATION_CANCELED': No scheme supplied. Perhaps you meant https://ACTIVATION_CANCELED?

**Comment by Pixens** [comment]
I'll check

**Comment by IT21051470** [comment]
> I'll check

thanks <3

**Comment by goodkarma07** [comment]
@Pixens had this issue as well :/

**Comment by Pazuzu777** [comment]
not verifying, they added captcha or something

**Comment by Pixens** [comment]
I'll update at 60 stars

**Comment by Pixens** [comment]
Recoded tool, fixed the error.
