### ISSUE TITLE
Cant get new token after verify email

### ISSUE THREAD

**Issue by jinxx0** [Pixens/Discord-Token-Mail-Verifier#6]

**Comment by jinxx0** [comment]
[+] Added mail | MTE1MzMwMjE5MDYzNTYxNDIzMA.GACU1S.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[+] Verified email | MTE1MzMwMjE5MDYzNTYxNDIzMA.GACU1S!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After verify discord changes token

**Comment by Pixens** [comment]
Uhh, it should save the new token and print it. Works for me
