### ISSUE TITLE
    ImportError: Installing this module requires OpenSSL python bindings

### ISSUE THREAD

**Issue by hectorjimenez11** [Pixens/Discord-Token-Mail-Verifier#7]
![image](https://github.com/Pixens/Discord-Token-Mail-Verifier/assets/113374983/096f3437-9468-4d23-92ee-36958965f84f)
Could anyone help me with this error? Thanks.

**Comment by hectorjimenez11** [comment]
It keeps giving error even after installing 'pip install pyOpenSSL'

**Comment by hectorjimenez11** [comment]
Also another error it gives me on the main.py its this, i put the api key and everything, i dont know if its related with the previous error.
![image](https://github.com/Pixens/Discord-Token-Mail-Verifier/assets/113374983/cc6f481a-953b-424b-8aeb-ba4be8ddf6e5)

**Comment by Pixens** [comment]
pip install kopeechka

**Comment by hectorjimenez11** [comment]
> pip install kopeechka

Thanks, it worked and now I dont have that problem but I have a new question , what makes a toke a "bad token" i put a list of tokens to verify and all of them are bad 
![image](https://github.com/Pixens/Discord-Token-Mail-Verifier/assets/113374983/5266d73b-416b-4ae6-9460-9082b441398e)
Thanks.

**Comment by Pixens** [comment]
Umm probably something with kopeechka. I think you're API key is invalid
